### ISSUE TITLE
How to run on pseudo distributed mode

### ISSUE THREAD

**Issue by buddhikac96** [autopear/Intellij-Hadoop#2]
First, thanks for the project. This works perfectly on my machine.

I want to know how can I run this project in pseudo-distributed mode on my laptop. I am using ubuntu 20.04.

Thanks.

**Comment by autopear** [comment]
I'm not sure if this is possible by maven or a single jar file. But you can always setup a hadoop environment on your local machine, so you can easily run any hadoop program in single node mode or pseudo distributed mode. See https://hadoop.apache.org/docs/stable/hadoop-project-dist/hadoop-common/SingleCluster.html#Pseudo-Distributed_Operation

**Comment by buddhikac96** [comment]
@autopear Thanks and closing the issue.
